server:
port: 8080
spring:
application:
name: auth-demo
security:
jwt:
secret-key: ${JWT_SECRET_KEY}
expiration: 7200000
config:
import: optional:file:.env[.properties]
datasource:
url: jdbc:${DATABASE_URL}
username: ${DATABASE_USERNAME}
password: ${DATABASE_PASSWORD}
driver-class-name: org.postgresql.Driver
jpa:
hibernate:
ddl-auto: update
show-sql: true
properties:
hibernate:
format_sql: true
logging:
level:
org:
hibernate:
SQL: DEBUG
type:
descriptor:
sql:
BasicBinder: TRACE